# Generated by Django 4.1.7 on 2023-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_user_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
