# Generated by Django 4.1.7 on 2023-03-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_remove_savedlocation_user_savedlocation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlocation',
            name='user',
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weather.user'),
        ),
    ]
